{
 "title": "Rancher Exporter Metrics",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Installed Rancher Version",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "installed_rancher_version" }
   ]
  },
  {
   "title": "Clusters Connected",
   "type": "stat",
   "description": "Note, this does not include the \"Local\" cluster",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cluster_connected)" }
   ]
  },
  {
   "title": "Clusters Disconnected",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cluster_not_connected)" }
   ]
  },
  {
   "title": "Latest Rancher Version",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "latest_rancher_version" }
   ]
  },
  { "title": "Cluster Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Managed K8s Clusters by Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rancher_managed_rke_clusters)",
     "legendFormat": "RKE1"
    },
    {
     "expr": "sum(rancher_managed_rke2_clusters)",
     "legendFormat": "RKE2"
    },
    {
     "expr": "sum(rancher_managed_k3s_clusters)",
     "legendFormat": "K3s"
    },
    {
     "expr": "sum(rancher_managed_eks_clusters)",
     "legendFormat": "EKS"
    },
    {
     "expr": "sum(rancher_managed_aks_clusters)",
     "legendFormat": "AKS"
    },
    {
     "expr": "sum(rancher_managed_gke_clusters)",
     "legendFormat": "GKE"
    }
   ]
  },
  {
   "title": "K8s Clusters",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "targets": [
    { "expr": "cluster_k8s_version" }
   ]
  },
  {
   "title": "Managed K8s clusters by Version",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (Version) (cluster_k8s_version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "List of Connected Clusters",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "targets": [
    { "expr": "cluster_connected == 1" }
   ]
  },
  {
   "title": "List of Disconnected Clusters",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 16 },
   "targets": [
    { "expr": "cluster_not_connected == 1" }
   ]
  },
  { "title": "Rancher Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Rancher Users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rancher_users" }
   ]
  },
  {
   "title": "Rancher Tokens",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rancher_tokens" }
   ]
  },
  { "title": "Global Values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Number of Managed Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rancher_managed_nodes" }
   ]
  },
  {
   "title": "Number of Managed Clusters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rancher_managed_clusters" }
   ]
  }
 ]
}